import { useState } from 'react';
import { motion } from 'framer-motion';
import { Wand2 } from 'lucide-react';
import Button from '../ui/Button';
import { QUIZ_DIFFICULTIES } from '../../utils/constants';

export default function QuizGenerator({ notes = [], onGenerate, generating = false }) {
  const [topic, setTopic] = useState('');
  const [noteId, setNoteId] = useState('');
  const [difficulty, setDifficulty] = useState('medium');
  const [numQuestions, setNumQuestions] = useState(5);

  const handleSubmit = (e) => {
    e.preventDefault();
    onGenerate({
      topic: topic.trim() || undefined,
      noteId: noteId || undefined,
      difficulty,
      numQuestions: Number(numQuestions),
    });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label className="mb-1.5 block text-xs font-medium text-slate-400">Topic (optional)</label>
        <input
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          placeholder="e.g. Newton's laws of motion"
          className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-parchment outline-none placeholder:text-slate-500 focus:border-amber-400/60"
        />
      </div>

      {notes.length > 0 && (
        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-400">Base on a note (optional)</label>
          <select
            value={noteId}
            onChange={(e) => setNoteId(e.target.value)}
            className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-parchment outline-none focus:border-amber-400/60"
          >
            <option value="" className="bg-void">General knowledge / any topic</option>
            {notes.map((n) => (
              <option key={n._id || n.id} value={n._id || n.id} className="bg-void">
                {n.title || n.filename}
              </option>
            ))}
          </select>
        </div>
      )}

      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-400">Difficulty</label>
          <select
            value={difficulty}
            onChange={(e) => setDifficulty(e.target.value)}
            className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm capitalize text-parchment outline-none focus:border-amber-400/60"
          >
            {QUIZ_DIFFICULTIES.map((d) => (
              <option key={d} value={d} className="bg-void capitalize">
                {d}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label className="mb-1.5 block text-xs font-medium text-slate-400">Questions</label>
          <select
            value={numQuestions}
            onChange={(e) => setNumQuestions(e.target.value)}
            className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm text-parchment outline-none focus:border-amber-400/60"
          >
            {[5, 10, 15, 20].map((n) => (
              <option key={n} value={n} className="bg-void">
                {n} questions
              </option>
            ))}
          </select>
        </div>
      </div>

      <Button type="submit" icon={Wand2} loading={generating} className="w-full">
        {generating ? 'Generating with AI...' : 'Generate quiz'}
      </Button>
      <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center text-xs text-slate-500">
        Every quiz is freshly generated by your AI tutor, never the same set twice.
      </motion.p>
    </form>
  );
}
